apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: '1.11.4'
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    hubble:
      # See https://docs.cilium.io/en/stable/gettingstarted/hubble_setup/
      relay:
        enabled: true
      ui:
        enabled: true
    encryption:
      # See https://docs.cilium.io/en/stable/gettingstarted/encryption-wireguard/
      enabled: true
      type: wireguard
    l7Proxy: false

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
        nginx.ingress.kubernetes.io/auth-signin: {{ printf "https://%s.%s/oauth2/start" .Values.subdomains.oauth2_proxy .Values.domain }}
        nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
      hosts:
        - host: {{ printf "%s.%s" .Values.subdomains.cilium_ui .Values.domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - {{ printf "%s.%s" .Values.subdomains.cilium_ui .Values.domain }}
          secretName: cilium-cert