config:
  clientID: oauth2_proxy
  clientSecret: "RXZwSU1oZEdpcCZiT1lMakdMMyk="
  cookieSecret: RSFc1gBhd6Xa0zHbfthGQc9HhxYxUawU
  configFile: |-
    pass_access_token = true
    pass_authorization_header = true
    scopes = ["openid", "profile", "email", "groups", "federated:id", "audience:server:client_id:k8s"]
# -> see https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#config-file
# and https://dexidp.io/docs/custom-scopes-claims-clients/#scopes
# and https://dexidp.io/docs/custom-scopes-claims-clients/#cross-client-trust-and-authorized-party
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: acme
  hosts:
    - host: auth.test.cloudlane.one
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - auth.test.cloudlane.one
      secretName: oauth2-proxy-cert
