kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  labels:
      velero.io/csi-volumesnapshot-class: "true"
  name: longhorn
driver: driver.longhorn.io
deletionPolicy: Delete
