# httpproxy-multiple-headers.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  virtualhost:
    fqdn: {{ printf "%s.%s" .Values.root.subdomains.argocd .Values.root.domain }}
    tls:
      secretName: argocd-tls
  routes:
    # Translated from this Traefik example: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#ingressroute-crd
    - conditions:
      - header:
          name: Content-Type
          contains: application/grpc
      services:
        - name: argocd-server
          port: 80
          protocol: h2c
    - services:
        - name: argocd-server
          port: 80
