{{ if .Values.k3s_setup_run }}
flannel-backend: none # for Cilium
disable-network-policy: true # for Cilium
disable: 
  - traefik # for NGINX Proxy
kube-apiserver-arg:
  # see [Dex Docs](https://dexidp.io/docs/kubernetes/#configuring-the-openid-connect-plugin)
  # and [K8S Auth Docs](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server)
  # and [Kubelogin Docs](https://github.com/int128/kubelogin/blob/master/docs/setup.md#4-set-up-the-kubernetes-api-server)
  - {{ printf "--oidc-issuer-url=https://%s.%s" .Values.subdomains.dex .Values.domain }}
  - --oidc-client-id=kubelogin
  - --oidc-username-claim=email
  - --oidc-groups-claim=groups
{{ end }}