apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
spec:
  chart: longhorn
  repo: https://charts.longhorn.io
  version: 1.2.4
  targetNamespace: longhorn-system
  set:
    defaultSettings:
      # See https://longhorn.io/docs/1.2.4/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-aws-s3-backupstore
      backupTarget: {{ printf "s3://%s@%s/" .Values.s3_backup.bucket ``.Values.s3_backup.region }}
      backupTargetCredentialSecret: s3-secret