kind: Namespace
apiVersion: v1
metadata:
name: longhorn-system
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: longhorn-system
type: Opaque
data:
  # See https://longhorn.io/docs/1.2.4/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-aws-s3-backupstore
  AWS_ACCESS_KEY_ID: {{ .Values.s3_backup.access_key.id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3_backup.access_key.secret | b64enc | quote }}
  AWS_ENDPOINTS: {{ .Values.s3_backup.endpoint | b64enc | quote }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-dashboard
      version: '1.2.4'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      # See https://longhorn.io/docs/1.2.4/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-aws-s3-backupstore
      backupTarget: {{ printf "s3://%s@%s/" .Values.s3_backup.bucket ``.Values.s3_backup.region }}
      backupTargetCredentialSecret: s3-secret

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
        nginx.ingress.kubernetes.io/auth-signin: {{ printf "https://%s.%s/oauth2/start" .Values.root.subdomains.oauth2_proxy .Values.root.domain }}
        nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
      hosts:
        - host: {{ printf "%s.%s" .Values.root.subdomains.longhorn_ui .Values.root.domain }}
      tls:
        - hosts:
            - {{ printf "%s.%s" .Values.root.subdomains.longhorn_ui .Values.root.domain }}
          secretName: longhorn-cert
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: main-backup
  namespace: longhorn-system
spec:
  # See https://longhorn.io/docs/1.2.4/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-longhorn-recurringjob
  cron: "0 0 * * *" # Every day at 12:00 AM
  task: "backup"
  groups:
  - default
  retain: 2
  concurrency: 1
