apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: longhorn-system
type: Opaque
data:
  # See https://longhorn.io/docs/1.2.4/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-aws-s3-backupstore
  AWS_ACCESS_KEY_ID: {{ .Values.s3_backup.access_key.id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3_backup.access_key.secret | b64enc | quote }}
  AWS_ENDPOINTS: {{ .Values.s3_backup.endpoint | b64enc | quote }}