apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crd-config
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/crd-config
      sourceRef:
        kind: GitRepository
        name: k3sx
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: longhorn
      namespace: longhorn-system
  values:
    letsencrypt_email: {{ .Values.email.admin_address | quote }}
    test_run: {{ .Values.test_run }}
