{{ if .Values.k3s_setup_run }}
users:
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - {{ printf "--oidc-issuer-url=%s" (include "urls.oidc_issuer" . ) }}
          - {{ printf "--oidc-client-id=%s" (include "names.oidc_client" . ) }}
          - {{ printf "--oidc-client-secret=%s" (include "secrets.oidc_client" . ) }}
          - --oidc-extra-scope="email groups profile openid"
        command: kubectl
        env: null
        provideClusterInfo: false
contexts:
  - context:
      cluster: default
      user: oidc
    name: oidc
current-context: oidc
{{ end }}