kind: Namespace
apiVersion: v1
metadata:
  name: nginx-ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.1.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  dependsOn:
    - name: cilium
      namespace: kube-system
  values:
    controller:
      ingressClassResource:
        default: true
      extraArgs:
        enable-ssl-passthrough: "true"
