{{- define "hosts.weave_gitops" -}}
{{ printf "%s.%s" .Values.subdomains.weave_gitops .Values.domain }}
{{- end -}}
{{- define "urls.weave_gitops_callback" -}}
{{ printf "https://%s/oauth2/callback" (include "hosts.weave_gitops" .) }}
{{- end -}}

kind: Namespace
apiVersion: v1
metadata:
  name: wego-system
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-auth
  namespace: flux-system
type: Opaque
data:
  # See https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/#login-via-an-oidc-provider
  issuerURL: {{ include "urls.oidc_issuer" . | b64enc }}
  clientID: {{ include "names.oidc_client" . | b64enc }}
  clientSecret: {{ include "secrets.oidc_client" . | b64enc }}
  redirectURL: {{ include "urls.weave_gitops_callback" . | b64enc }}
  tokenDuration: {{ b64enc "1h0m0s" }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wego-admin-role
  namespace: flux-system
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - secrets
      - pods
  - verbs:
      - get
      - list
    apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
  - verbs:
      - get
      - list
      - patch
    apiGroups:
      - kustomize.toolkit.fluxcd.io
    resources:
      - kustomizations
  - verbs:
      - get
      - list
      - patch
    apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
  - verbs:
      - get
      - list
      - patch
    apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - buckets
      - helmcharts
      - gitrepositories
      - helmrepositories
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - events
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wego-admin-rolebinding
  namespace: flux-system
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.adminGroup | quote }}
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wego-admin-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wego-admin-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods" ]
    verbs: [ "get", "list" ]
  - apiGroups: ["apps"]
    resources: [ "deployments", "replicasets"]
    verbs: [ "get", "list" ]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [ "kustomizations" ]
    verbs: [ "get", "list", "patch" ]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [ "helmreleases" ]
    verbs: [ "get", "list", "patch" ]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories" ]
    verbs: [ "get", "list", "patch" ]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-admin-cluster-rolebinding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.adminGroup | quote }}
roleRef:
  kind: ClusterRole
  name: wego-admin-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: wego-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/gitops-server
      # no version, use latest revision of main branch instead
      sourceRef:
        kind: GitRepository
        name: weave-gitops
        namespace: flux-system
  dependsOn:
    - name: nginx-ingress
      namespace: nginx-ingress
    - name: cert-manager
      namespace: cert-manager
    - name: external-dns
      namespace: external-dns
    - name: dex
      namespace: sso
  values:
    image:
      tag: latest
    rbac:
      create: true
      impersonationResources: ["users", "groups"]
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
      hosts:
        - host: {{ include "hosts.weave_gitops" . }}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - {{ include "hosts.weave_gitops" . }}
          secretName: weave-gitops-cert
