apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: main-backup
  namespace: longhorn-system
spec:
  # See https://longhorn.io/docs/1.2.4/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-longhorn-recurringjob
  cron: "0 0 * * *" # Every day at 12:00 AM
  task: "backup"
  groups:
  - default
  retain: 2
  concurrency: 1