kind: Namespace
apiVersion: v1
metadata:
  name: backup-system
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-credentials
  namespace: backup-system
type: Opaque
data:
  cloud: {{ printf "[default]\naws_access_key_id=%s\naws_secret_access_key=%s" .Values.s3_backup.access_key.id .Values.s3_backup.access_key.secret | b64enc }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-validation-webhook
  namespace: backup-system
spec:
  interval: 5m
  chart:
    spec:
      chart: snapshot-validation-webhook
      version: '1.5.1'
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: backup-system
spec:
  interval: 5m
  chart:
    spec:
      chart: snapshot-controller
      version: '1.5.1'
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: flux-system
  dependsOn:
    - name: snapshot-validation-webhook
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: backup-system
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: '2.30.1'
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  dependsOn:
    - name: snapshot-controller
  values:
    credentials:
      existingSecret: s3-backup-credentials
    initContainers:
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.3.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.5.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: {{ .Values.s3_backup.bucket }}
        prefix: velero
        config:
          region: {{ .Values.s3_backup.region }}
          s3Url: {{ printf "https://%s" .Values.s3_backup.endpoint }}
      volumeSnapshotLocation:
        name: default
        config:
          region: {{ .Values.s3_backup.region }}
      features: EnableCSI
    snapshotsEnabled: true
    schedules:
      full-backup:
        disabled: false
        schedule: "0 0 * * *"
        useOwnerReferencesInBackup: false
        template:
          includedNamespaces:
            - "*"
          includeClusterResources: true
          snapshotVolumes: true