apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-issuer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/sub/cluster-issuer
      sourceRef:
        kind: GitRepository
        name: k3sx
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: ingress-system
  values:
    letsencrypt_email: {{ .Values.admin.email | quote }}
    test_run: {{ .Values.test_run }}
