apiVersion: v1
kind: Secret
metadata:
  name: oidc-client
  namespace: kube-system
type: Opaque
data:
  secret: {{ include "common.secrets.passwords.manage" (dict "secret" "oidc-client" "key" "secret" "providedValues" (list "") "context" $) | b64enc }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sso-connector
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/connector
      sourceRef:
        kind: GitRepository
        name: domain-sso
        namespace: flux-system
  dependsOn:
    - name: sso-provider
      namespace: sso-system
  values:
    ssoProviderNamespace: sso-system
    configSecretName: sso-config
    clients:
      oidc:
        - id: kube-oidc
          redirectURIs:
            - http://localhost:8000
            - http://localhost:18000
          secretName: oidc-client
