domain: "" # The public root domain of this cluster (e.g. "example.org")
clusterName: "" # Name for this cluster (unique for the supplied domain)

org:
  name: "" # The full name of your organization
  defaultLocale: "en_US"
  logoURL: ""

admin:
  idp:
    # See https://dexidp.io/docs/connectors/
    type: "github"
    clientID: ""
    clientSecret: ""
    issuerURL: ""
  group: "" # A label identifying the group provided by your IDP, which is to be granted admin privileges (org:team for GitHub)
  email: "" # Admin email address (for email notifications and initial admin accounts)
  password: "" # Password for initial admin account

s3_backup:
  endpoint: "" # Domain without protocol of your S3 endpoint (e.g. "s3.example.org")
  region: "eu-central-1" # Required by Longhorn, just leave the default if you don't have zones
  bucket: "" # Name of your S3 backup bucket
  access_key:
    id: "" # Your S3 access key id
    secret: "" # Your S3 access key secret

external_dns: # These settings are piped directly into the external-dns helm chart config
  # Please supply the type of your DNS provider and according config.
  # For a list of available providers see: https://github.com/kubernetes-sigs/external-dns#the-latest-release
  provider: digitalocean
  digitalocean:
    apiToken: ""

subdomains:
  # Under which subdomains of your supplied root domain should the various services run? (Created automatically by external-dns)
  k8s_dashboard: "cluster"
  longhorn_ui: "storage"
  cilium_ui: "network"

k3s_setup_run: false # If true, renders k3s YAML config locally to be used by k3sup in cluster setup

repo:
  url: "https://github.com/lorenzo-w/k3sx"
  branch: "main"

letsencrypt_staging: false # If true, uses Letsencrypt staging APIs instead of production ones. Prevents execeeding API limits.
