kind: Namespace
apiVersion: v1
metadata:
name: wego-system
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-auth
  namespace: wego-system
type: Opaque
data:
  # See https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/#login-via-an-oidc-provider
  issuerURL: {{ printf "https://%s.%s" .Values.root.subdomains.dex .Values.root.domain }}
  clientID: k8s
  clientSecret: {{ derivePassword 1 "maximum" .Values.secretSeed "k8s-client" .Values.domain | b64enc | quote }}
  redirectURL: {{ printf "https://%s.%s/oauth2/callback" .Values.root.subdomains.weave_gitops .Values.root.domain }}
  # tokenDuration: "1h0m0s"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      version: '0.8.0'
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
      hosts:
        - host: {{ printf "%s.%s" .Values.root.subdomains.weave_gitops .Values.root.domain }}
      tls:
        - hosts:
            - {{ printf "%s.%s" .Values.root.subdomains.weave_gitops .Values.root.domain }}
          secretName: weave-gitops-cert
