apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kubeapps
      version: '9.0.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    {{ $url := printf "https://%s" .Values.hosts.kubeapps -}}
    ingress:
      enabled: true
      hostname: {{ .Values.hosts.kubeapps }}
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: acme
        nginx.ingress.kubernetes.io/auth-response-headers: Authorization
        nginx.ingress.kubernetes.io/auth-signin: {{ printf "%s?rd=%s" (include "get_sso_config" (dict "key" "authproxy_login_url" "context" $)) (urlquery $url) }}
        nginx.ingress.kubernetes.io/auth-url: {{ printf "%s?allowed_groups=%s" (include "get_sso_config" (dict "key" "authproxy_check_url" "context" $)) (include "get_sso_config" (dict "key" "admin_group" "context" $) | urlquery) }}
    authProxy:
      enabled: true
      external: true
      oauthLoginURI: {{ printf "%s?rd=%s" (include "get_sso_config" (dict "key" "authproxy_login_url" "context" $)) (urlquery $url) }}
      oauthLogoutURI: {{ include "get_sso_config" (dict "key" "authproxy_logout_url" "context" $) }}
      skipKubeappsLoginPage: true
